import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#8BA5B0',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    padding: 16,
  },
  container: {
    flex: 1,
    width: '100%',
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#1E1E1E',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    color: '#1E1E1E',
    textAlign: 'center',
    marginBottom: 24,
  },
  livesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  livesText: {
    fontSize: 18,
    color: '#1E1E1E',
    marginRight: 8,
  },
  calculatorEmoji: {
    fontSize: 24,
    marginHorizontal: 4,
  },
  livesCounter: {
    fontSize: 18,
    color: '#1E1E1E',
    marginLeft: 8,
  },
  cardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
    gap: 16,
  },
  cardContainer: {
    width: '48%',
    aspectRatio: 1,
    marginBottom: 16,
  },
  card: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backfaceVisibility: 'hidden',
  },
  cardBack: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backfaceVisibility: 'hidden',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E1E1E',
    marginBottom: 8,
    textAlign: 'center',
  },
  adImage: {
    width: '100%',
    height: '80%',
    borderRadius: 8,
  },
  explanationText: {
    fontSize: 14,
    color: '#1E1E1E',
    textAlign: 'center',
    marginBottom: 8,
  },
  fakeIndicator: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF4444',
  },
  completionMessage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  trophyIcon: {
    marginBottom: 16,
  },
  completionText: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  completionSubtext: {
    fontSize: 20,
    color: '#1E1E1E',
    marginBottom: 16,
    textAlign: 'center',
  },
  completionDetails: {
    fontSize: 16,
    color: '#1E1E1E',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 24,
  },
  statsContainer: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 16,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    padding: 12,
    borderRadius: 12,
    gap: 8,
  },
  statText: {
    fontSize: 16,
    color: '#1E1E1E',
  },
  retryButton: {
    backgroundColor: '#F5F5F5',
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
  },
  retryText: {
    fontSize: 16,
    color: '#4CAF50',
  },
});