import { Platform, StyleSheet, Dimensions } from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#8BA5B0',
      paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    container: {
      flex: 1,
    },
    mainScrollView: {
      flex: 1,
    },
    mainScrollViewContent: {
      padding: windowWidth * 0.05,
      paddingBottom: windowHeight * 0.1,
    },
    title: {
      fontSize: windowWidth < 380 ? 24 : 32,
      fontWeight: 'bold',
      color: '#1E1E1E',
      textAlign: 'center',
      marginTop: windowHeight * 0.02,
      marginBottom: windowHeight * 0.02,
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    subtitle: {
      fontSize: windowWidth < 380 ? 14 : 18,
      color: '#1E1E1E',
      textAlign: 'center',
      marginBottom: windowHeight * 0.02,
      opacity: 0.8,
      paddingHorizontal: '5%',
    },
    gameContainer: {
      flex: 1,
      backgroundColor: '#34495E',
      borderRadius: 20,
      overflow: 'hidden',
      minHeight: windowHeight * 0.65,
      padding: windowWidth * 0.03,
      borderWidth: 2,
      borderColor: '#4CAF50',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.3,
      shadowRadius: 4.65,
      elevation: 8,
    },
    messagesContainer: {
      flex: 1,
      maxHeight: windowHeight * 0.55,
      backgroundColor: '#ECF0F1',
      borderRadius: 15,
      padding: windowWidth * 0.03,
    },
    messagesContent: {
      paddingVertical: windowWidth * 0.03,
      paddingHorizontal: windowWidth * 0.02,
    },
    messageContainer: {
      flexDirection: 'row',
      marginBottom: 15,
      alignItems: 'flex-end',
      opacity: 1,
      transform: [{ scale: 1 }],
      marginHorizontal: windowWidth * 0.02,
    },
    botMessage: {
      justifyContent: 'flex-start',
    },
    userMessage: {
      justifyContent: 'flex-end',
    },
    avatarContainer: {
      marginRight: 12,
      marginBottom: 4,
    },
    avatarBackground: {
      backgroundColor: '#34495E',
      borderRadius: 25,
      padding: 8,
      borderWidth: 2,
      borderColor: '#4CAF50',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    onlineIndicator: {
      position: 'absolute',
      right: 0,
      bottom: 0,
      width: 12,
      height: 12,
      backgroundColor: '#4CAF50',
      borderRadius: 6,
      borderWidth: 2,
      borderColor: '#1E1E1E',
    },
    messageBubble: {
      maxWidth: '75%',
      padding: 12,
      borderRadius: 16,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    botBubble: {
      backgroundColor: '#3498DB',
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: '#2980B9',
    },
    userBubble: {
      backgroundColor: '#4CAF50',
      borderBottomRightRadius: 4,
      borderWidth: 1,
      borderColor: '#388E3C',
    },
    messageText: {
      color: '#FFFFFF',
      fontSize: 16,
      lineHeight: 22,
      letterSpacing: 0.3,
    },
    inputContainer: {
      borderTopWidth: 1,
      borderTopColor: '#2980B9',
      marginTop: 10,
    },
    textInputContainer: {
      flexDirection: 'row',
      padding: 12,
      backgroundColor: '#34495E',
      alignItems: 'center',
      borderRadius: 15,
    },
    textInput: {
      flex: 1,
      backgroundColor: '#2C3E50',
      borderRadius: 20,
      paddingHorizontal: 15,
      paddingVertical: 12,
      color: '#FFFFFF',
      marginRight: 10,
      borderWidth: 1,
      borderColor: '#4CAF50',
    },
    sendButton: {
      backgroundColor: '#4CAF50',
      width: 45,
      height: 45,
      borderRadius: 22.5,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    optionsContainer: {
      padding: 12,
      backgroundColor: '#34495E',
      borderRadius: 15,
    },
    optionButton: {
      padding: 14,
      borderRadius: 12,
      marginBottom: 10,
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      borderWidth: 1,
    },
    optionText: {
      color: '#FFFFFF',
      fontSize: 16,
      textAlign: 'center',
      fontWeight: '500',
    },
    livesContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: windowHeight * 0.02,
      backgroundColor: '#1E1E1E',
      padding: windowWidth * 0.02,
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    livesText: {
      fontSize: 16,
      color: '#8BA5B0',
      fontWeight: 'bold',
    },
    calculatorEmoji: {
      fontSize: 20,
      marginHorizontal: 4,
    },
    livesCounter: {
      fontSize: 16,
      color: '#8BA5B0',
      fontWeight: 'bold',
      marginLeft: 8,
    },
    completionMessage: {
      position: 'absolute',
      top: '40%',
      left: '5%',
      right: '5%',
      backgroundColor: '#1E1E1E',
      padding: 30,
      borderRadius: 20,
      alignItems: 'center',
      elevation: 10,
    },
    warningIcon: {
      marginBottom: 20,
    },
    trophyIcon: {
      marginBottom: 20,
    },
    completionText: {
      fontSize: 28,
      fontWeight: 'bold',
      marginBottom: 10,
      textAlign: 'center',
    },
    completionSubtext: {
      fontSize: 18,
      color: '#8BA5B0',
      textAlign: 'center',
      marginBottom: 15,
    },
    completionDetails: {
      fontSize: 16,
      color: '#8BA5B0',
      textAlign: 'center',
      opacity: 0.8,
      marginBottom: 20,
    },
    retryButton: {
      backgroundColor: '#1E1E1E',
      padding: 15,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: '#FF4444',
      marginTop: 10,
    },
    buttonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    retryText: {
      color: '#4CAF50',
      fontWeight: 'bold',
      fontSize: 16,
      marginLeft: 10,
    },
    typingBubble: {
      backgroundColor: '#3498DB',
      paddingVertical: 10,
      paddingHorizontal: 15,
      opacity: 0.8,
    },
    typingText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontStyle: 'italic',
    },
  })