import { StyleSheet } from 'react-native';
const passwordGameStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#8BA5B0',
  },
  card: {
    flex: 1,
    backgroundColor: '#1E1E1E',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#8BA5B0',
    textAlign: 'center',
    marginBottom: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  inputContainer: {
    marginBottom: 24,
  },
  label: {
    fontSize: 18,
    color: '#8BA5B0',
    marginBottom: 8,
    fontWeight: '600',
  },
  input: {
    backgroundColor: '#333',
    borderRadius: 12,
    padding: 16,
    color: '#8BA5B0',
    fontSize: 16,
    borderWidth: 2,
    borderColor: '#6B8590',
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#6B8590',
  },
  passwordInput: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  eyeIcon: {
    padding: 16,
  },
  strengthContainer: {
    height: 10,
    backgroundColor: '#333',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#6B8590',
  },
  strengthBar: {
    height: '100%',
  },
  scoreText: {
    fontSize: 20,
    color: '#8BA5B0',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '600',
  },
  suggestionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#333',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#6B8590',
  },
  suggestionButtonText: {
    color: '#8BA5B0',
    fontSize: 18,
    fontWeight: '600',
    marginRight: 8,
  },
  suggestionArrow: {
    marginLeft: 8,
  },
  suggestionsContainer: {
    overflow: 'hidden',
  },
  ruleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: '#6B8590',
  },
  ruleText: {
    flex: 1,
    color: '#8BA5B0',
    marginLeft: 12,
    fontSize: 16,
  },
  copyButton: {
    backgroundColor: '#6B8590',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 20,
    borderWidth: 2,
    borderColor: '#8BA5B0',
  },
  copyButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
});

export default passwordGameStyles;
