import { StatusBar, StyleSheet } from 'react-native';

export const platformerGameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },

  labBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#1a1a1a',
  },
  gridLines: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  horizontalLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
  },
  verticalLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
  },
  securityStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 5,
    margin: 10,
  },
  securityLabel: {
    color: '#fff',
    fontSize: 12,
    marginRight: 10,
  },
  securityIndicator: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 3,
  },
  securityText: {
    fontWeight: 'bold',
    fontSize: 12,
  },
  securityLow: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    borderWidth: 1,
    borderColor: '#FF5252',
  },
  securityMedium: {
    backgroundColor: 'rgba(255, 193, 7, 0.2)',
    borderWidth: 1,
    borderColor: '#FFC107',
  },
  securityHigh: {
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  mainContent: {
    flexDirection: 'row',
    padding: 10,
    justifyContent: 'space-between',
  },
  leftSection: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 80,
  },
  serverRack: {
    width: '90%',
    aspectRatio: 0.5,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 5,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#333',
  },
  server: {
    height: '12%',
    backgroundColor: '#333',
    borderRadius: 4,
    padding: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  serverLights: {
    flexDirection: 'row',
    gap: 3,
  },
  light: {
    width: 4,
    height: 4,
    borderRadius: 2,
  },
  lightGreen: {
    backgroundColor: '#4CAF50',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  lightBlue: {
    backgroundColor: '#2196F3',
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  networkCables: {
    width: '100%',
    height: 50,
    justifyContent: 'space-around',
    marginTop: 10,
  },
  cable: {
    height: 2,
    width: '80%',
    marginVertical: 2,
  },
  centerSection: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  workstationArea: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignItems: 'center',
    padding: 10,
  },
  desk: {
    width: '40%',
    aspectRatio: 1.5,
    padding: 5,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    margin: 5,
  },
  leftDesk: {
    marginRight: 10,
  },
  rightDesk: {
    marginLeft: 10,
  },
  topRow: {
    marginBottom: 10,
  },
  bottomRow: {
    marginTop: 10,
  },
  monitor: {
    width: '90%',
    height: '60%',
    alignItems: 'center',
  },
  screen: {
    width: '100%',
    height: '85%',
    backgroundColor: '#111',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#444',
    padding: 5,
    justifyContent: 'space-around',
    position: 'relative',
  },
  solvedScreen: {
    backgroundColor: '#1a4a1a',
    borderColor: '#2d5a2d',
  },
  screenContent: {
    height: 4,
    backgroundColor: '#333',
    borderRadius: 2,
  },
  checkmark: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -10 }, { translateY: -10 }],
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(76, 175, 80, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmarkText: {
    color: '#4CAF50',
    fontSize: 14,
    fontWeight: 'bold',
  },
  monitorStand: {
    width: '20%',
    height: '15%',
    backgroundColor: '#444',
    borderRadius: 4,
  },
  keyboard: {
    width: '80%',
    height: '20%',
    backgroundColor: '#333',
    marginTop: 5,
    borderRadius: 4,
    padding: 3,
    justifyContent: 'space-around',
  },
  keyboardRow: {
    height: 1,
    backgroundColor: '#444',
    borderRadius: 0.5,
  },
  mouse: {
    position: 'absolute',
    right: '15%',
    bottom: '15%',
    width: 10,
    height: 15,
    backgroundColor: '#444',
    borderRadius: 5,
  },
  rightSection: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    maxWidth: 100,
  },
  securityMonitors: {
    width: '100%',
    height: '40%',
    justifyContent: 'space-between',
    gap: 10,
  },
  securityMonitor: {
    width: '90%',
    aspectRatio: 1.5,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    padding: 3,
    borderWidth: 1,
    borderColor: '#333',
  },
  monitorScreen: {
    flex: 1,
    backgroundColor: '#111',
    borderRadius: 4,
    padding: 2,
    justifyContent: 'space-around',
  },
  monitorGraph: {
    height: 20,
    backgroundColor: 'rgba(33, 150, 243, 0.2)',
    borderRadius: 4,
    borderTopWidth: 1,
    borderColor: '#2196F3',
  },
  monitorData: {
    height: 2,
    backgroundColor: '#2196F3',
    borderRadius: 1,
    marginVertical: 1,
  },
  securityFeatures: {
    width: '100%',
    alignItems: 'center',
    gap: 10,
  },
  camera: {
    width: 20,
    height: 25,
    alignItems: 'center',
  },
  cameraLens: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    backgroundColor: '#111',
    borderWidth: 1,
    borderColor: '#444',
  },
  cameraBody: {
    width: 8,
    height: 10,
    backgroundColor: '#333',
    marginTop: -3,
  },
  keypad: {
    width: 40,
    height: 50,
    backgroundColor: '#333',
    borderRadius: 4,
    padding: 3,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keypadButton: {
    width: 10,
    height: 10,
    backgroundColor: '#444',
    borderRadius: 2,
  },
  firewallStatus: {
    width: '80%',
    alignItems: 'center',
    marginTop: 10,
  },
  firewallLabel: {
    color: '#fff',
    fontSize: 10,
    marginBottom: 3,
  },
  firewallIndicator: {
    width: '100%',
    height: 15,
    borderRadius: 7.5,
    borderWidth: 1,
  },
  firewallActive: {
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderColor: '#4CAF50',
  },
  firewallInactive: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    borderColor: '#FF5252',
  },
  staticEngineer: {
    position: 'absolute',
    width: 30,
    height: 60,
    alignItems: 'center',
    zIndex: 10,
    transform: [{ scale: 0.8 }],
  },
  engineerBody: {
    position: 'absolute',
    top: -15,
  },
  chair: {
    width: 40,
    height: 50,
    position: 'relative',
  },
  chairBack: {
    position: 'absolute',
    width: 30,
    height: 35,
    backgroundColor: '#444',
    borderRadius: 5,
    top: 0,
    left: 5,
  },
  chairSeat: {
    position: 'absolute',
    width: 40,
    height: 10,
    backgroundColor: '#444',
    borderRadius: 5,
    bottom: 15,
  },
  chairBase: {
    position: 'absolute',
    width: 10,
    height: 15,
    backgroundColor: '#333',
    bottom: 5,
    left: 15,
  },
  chairWheels: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  wheel: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#222',
  },
  sittingBody: {
    height: 30,
    transform: [{ translateY: 5 }],
  },
  sittingLegs: {
    height: 20,
    transform: [{ translateY: -5 }],
  },
  sittingLeg: {
    transform: [{ rotate: '90deg' }],
  },
  head: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFD5B5',
    position: 'relative',
  },
  hair: {
    position: 'absolute',
    top: -4,
    left: -2,
    width: 28,
    height: 18,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: '#4A3626',
    transform: [{ rotate: '-5deg' }],
  },
  face: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  glasses: {
    width: 16,
    height: 6,
    backgroundColor: '#2196F3',
    borderRadius: 3,
    marginTop: 4,
  },
  smile: {
    width: 8,
    height: 4,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: '#FF69B4',
    marginTop: 2,
  },
  body: {
    width: 30,
    height: 35,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    marginTop: -4,
    position: 'relative',
  },
  labCoat: {
    position: 'absolute',
    top: 0,
    left: -2,
    right: -2,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#EEEEEE',
  },
  badge: {
    position: 'absolute',
    top: 5,
    right: 2,
    width: 10,
    height: 15,
    backgroundColor: '#FF5252',
    borderRadius: 2,
  },
  legs: {
    width: 24,
    height: 25,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  leftLeg: {
    width: 10,
    height: '100%',
    backgroundColor: '#4A4A4A',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  rightLeg: {
    width: 10,
    height: '100%',
    backgroundColor: '#4A4A4A',
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#2a2a2a',
    padding: 15,
    borderRadius: 10,
    width: '90%',
    maxWidth: 350,
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  modalTitle: {
    color: '#4CAF50',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  questionText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
  },
  optionButton: {
    backgroundColor: '#3a3a3a',
    padding: 12,
    borderRadius: 5,
    marginVertical: 4,
    borderLeftWidth: 3,
    borderLeftColor: '#4CAF50',
  },
  optionText: {
    color: '#fff',
    fontSize: 14,
    textAlign: 'center',
  },

  progressContainer: {
    height: 20,
    backgroundColor: '#333',
    borderRadius: 10,
    margin: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#4CAF50',
  },
  progressText: {
    position: 'absolute',
    color: '#fff',
    fontSize: 12,
    width: '100%',
    textAlign: 'center',
    lineHeight: 20,
    fontWeight: 'bold',
  },
  hackerAttackBackground: {
    backgroundColor: '#2a1a1a',
  },
  interactiveDesk: {
    borderWidth: 2,
    borderColor: '#4CAF50',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  hackedScreen: {
    backgroundColor: '#4a1a1a',
    borderColor: '#FF5252',
  },
  hackerText: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -5 }, { translateY: -10 }],
    color: '#FF5252',
    fontSize: 20,
    fontWeight: 'bold',
  },
  alertBadge: {
    backgroundColor: '#FF5250',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    marginLeft: 10,
  },
  alertText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  tutorialOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  tutorialBox: {
    backgroundColor: '#2a2a2a',
    padding: 20,
    borderRadius: 10,
    width: '80%',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  tutorialTitle: {
    color: '#4CAF50',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  tutorialText: {
    color: '#fff',
    fontSize: 14,
    marginBottom: 15,
    textAlign: 'center',
    lineHeight: 20,
  },
  tutorialButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    alignSelf: 'center',
  },
  tutorialButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  successOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  successBox: {
    backgroundColor: '#2a2a2a',
    padding: 20,
    borderRadius: 10,
    width: '80%',
    borderWidth: 1,
    borderColor: '#4CAF50',
    alignItems: 'center',
  },
  successTitle: {
    color: '#4CAF50',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  successText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 15,
    textAlign: 'center',
  },
  successIcon: {
    width: 80,
    height: 80,
    backgroundColor: 'rgba(76, 175, 80, 0.2)',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#4CAF50',
    marginTop: 10,
  },
  successIconText: {
    fontSize: 40,
    color: '#4CAF50',
  },
  controls: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 5,
    borderRadius: 10,
    zIndex: 100,
  },
  controlRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlButton: {
    width: 35,
    height: 35,
    backgroundColor: 'rgba(76, 175, 80, 0.8)',
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 3,
  },
  controlButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  controlButtonSpacer: {
    width: 35,
    height: 35,
    margin: 3,
  },
  scoreContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 100,
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  scoreText: {
    color: '#4CAF50',
    fontWeight: 'bold',
    fontSize: 16,
  },
  malwareThreat: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
    borderWidth: 1,
    borderColor: '#FF5252',
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  malwareIcon: {
    fontSize: 18,
  },
  helpButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(76, 175, 80, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  helpButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  tipContainer: {
    position: 'absolute',
    top: '30%',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 100,
  },
  tipBox: {
    backgroundColor: 'rgba(76, 175, 80, 0.9)',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    maxWidth: '80%',
    borderWidth: 1,
    borderColor: '#fff',
  },
  tipText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
